export const metadata = {
  title: "Events",
  description: "Generated by create next app",
};

export default function EventLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gradient-to-r from-[#36D1DC] to-[#5b86e5] text-black">
      {children}
    </div>
  );
}
