export const metadata = {
  title: "Events",
  description: "Generated by create next app",
};

export default function EventLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen w-full bg-gradient-to-r from-yellow-300 to-purple-500 via-blue-400 animate-gradient-x text-black">
      {children}
    </div>
  );
}
