export const metadata = {
  title: "Form",
  description: "Generated by create next app",
};

export default function FormLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen w-full p-4 sm:p-8 flex justify-center bg-slate-100">
      {children}
    </div>
  );
}
