import { NextAuthProvider } from "../../../context/NextAuthProvider";
import Layout from "../components/Layout";

export const metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextAuthProvider>
      <Layout>{children}</Layout>
    </NextAuthProvider>
  );
}
